Pantarei\Bundle\Oauth2Bundle\Entity\AccessToken:
    type: entity
    table: access_token
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Entity\AccessTokenManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        access_token:
            type: string
            length: 255
        token_type:
            type: string
            length: 255
        client_id:
            type: string
            length: 255
        username:
            type: string
            length: 255
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
