Pantarei\Bundle\Oauth2Bundle\Model\AbstractAccessToken:
    type: entity
    table: access_token
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\AccessTokenManager
    fields:
        access_token:
            type: string
            length: 255
            column: access_token
        token_type:
            type: string
            length: 255
            column: token_type
        client_id:
            type: string
            length: 255
            column: client_id
        username:
            type: string
            length: 255
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
