Pantarei\Bundle\Oauth2Bundle\Entity\AccessToken:
    type: mappedSuperclass
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Entity\AccessTokenManager
    fields:
        access_token:
            type: string
            length: 255
        token_type:
            type: string
            length: 255
        client_id:
            type: string
            length: 255
        username:
            type: string
            length: 255
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
