Pantarei\Bundle\Oauth2Bundle\Entity\Authorize:
    type: mappedSuperclass
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Entity\AuthorizeManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        client_id:
            type: string
            length: 255
        username:
            type: string
            length: 255
        scope:
            type: array
    lifecycleCallbacks: {  }
