Pantarei\Bundle\Oauth2Bundle\Model\AbstractAuthorize:
    type: entity
    table: authorize
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\AuthorizeManager
    fields:
        client_id:
            type: string
            length: 255
            column: client_id
        username:
            type: string
            length: 255
        scope:
            type: array
    lifecycleCallbacks: {  }
