PantaRei\Bundle\OAuth2Bundle\Entity\Authorize:
    type: mappedSuperclass
    repositoryClass: PantaRei\Bundle\OAuth2Bundle\Entity\AuthorizeManager
    fields:
        client_id:
            type: string
            length: 255
        username:
            type: string
            length: 255
        scope:
            type: array
    lifecycleCallbacks: {  }
