Pantarei\Bundle\Oauth2Bundle\Model\Authorize:
    type: entity
    table: authorize
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Model\AuthorizeManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        client_id:
            type: string
            length: 255
            column: client_id
        username:
            type: string
            length: 255
        scope:
            type: array
    lifecycleCallbacks: {  }
