PantaRei\Bundle\OAuth2Bundle\Entity\Client:
    type: mappedSuperclass
    repositoryClass: PantaRei\Bundle\OAuth2Bundle\Entity\ClientManager
    fields:
        client_id:
            type: string
            length: 255
        client_secret:
            type: string
            length: 255
        redirect_uri:
            type: text
    lifecycleCallbacks: {  }
