Pantarei\Bundle\Oauth2Bundle\Entity\Client:
    type: mappedSuperclass
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Entity\ClientManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        client_id:
            type: string
            length: 255
        client_secret:
            type: string
            length: 255
        redirect_uri:
            type: text
    lifecycleCallbacks: {  }
