Pantarei\Bundle\Oauth2Bundle\Model\AbstractClient:
    type: entity
    table: client
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\ClientManager
    fields:
        client_id:
            type: string
            length: 255
            column: client_id
        client_secret:
            type: string
            length: 255
            column: client_secret
        redirect_uri:
            type: text
            column: redirect_uri
    lifecycleCallbacks: {  }
