Pantarei\Bundle\OAuth2Bundle\Entity\Client:
    type: entity
    table: client
    repositoryClass: Pantarei\Bundle\OAuth2Bundle\Entity\ClientManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        client_id:
            type: string
            length: 255
            column: client_id
        client_secret:
            type: string
            length: 255
            column: client_secret
        redirect_uri:
            type: blob
            column: redirect_uri
    lifecycleCallbacks: {  }
