Pantarei\Bundle\Oauth2Bundle\Model\AbstractCode:
    type: entity
    table: code
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\CodeManager
    fields:
        code:
            type: string
            length: 255
        client_id:
            type: string
            length: 255
            column: client_id
        username:
            type: string
            length: 255
        redirect_uri:
            type: text
            column: redirect_uri
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
