Pantarei\Bundle\Oauth2Bundle\Entity\Code:
    type: mappedSuperclass
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Entity\CodeManager
    fields:
        code:
            type: string
            length: 255
        client_id:
            type: string
            length: 255
        username:
            type: string
            length: 255
        redirect_uri:
            type: text
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
