Pantarei\Bundle\OAuth2Bundle\Entity\Code:
    type: entity
    table: code
    repositoryClass: Pantarei\Bundle\OAuth2Bundle\Entity\CodeManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
        client_id:
            type: string
            length: 255
            column: client_id
        username:
            type: string
            length: 255
        redirect_uri:
            type: string
            length: 255
            column: redirect_uri
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
