PantaRei\Bundle\OAuth2Bundle\Entity\RefreshToken:
    type: mappedSuperclass
    repositoryClass: PantaRei\Bundle\OAuth2Bundle\Entity\RefreshTokenManager
    fields:
        refresh_token:
            type: string
            length: 255
        client_id:
            type: string
            length: 255
        username:
            type: string
            length: 255
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
