Pantarei\Bundle\Oauth2Bundle\Model\AbstractRefreshToken:
    type: entity
    table: refresh_token
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\RefreshTokenManager
    fields:
        refresh_token:
            type: string
            length: 255
            column: refresh_token
        client_id:
            type: string
            length: 255
            column: client_id
        username:
            type: string
            length: 255
        expires:
            type: datetime
        scope:
            type: array
    lifecycleCallbacks: {  }
