PantaRei\Bundle\OAuth2Bundle\Entity\Scope:
    type: mappedSuperclass
    repositoryClass: PantaRei\Bundle\OAuth2Bundle\Entity\ScopeManager
    fields:
        scope:
            type: string
            length: 255
    lifecycleCallbacks: {  }
