Pantarei\Bundle\Oauth2Bundle\Model\AbstractScope:
    type: entity
    table: scope
    repositoryClass: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\ScopeManager
    fields:
        scope:
            type: string
            length: 255
    lifecycleCallbacks: {  }
