PantaRei\Bundle\OAuth2Bundle\Entity\Scope:
    type: entity
    table: scope
    repositoryClass: PantaRei\Bundle\OAuth2Bundle\Entity\ScopeManager
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        scope:
            type: string
            length: 255
    lifecycleCallbacks: {  }
