parameters:
    oauth2.model_manager.factory.class: Pantarei\Bundle\Oauth2Bundle\Doctrine\ORM\ModelManagerFactory

services:
    oauth2.model_manager.factory:
        class: %oauth2.model_manager.factory.class%
        arguments: ["@doctrine.orm.entity_manager", "%oauth2.model%"]
