parameters:
    pantarei_oauth2.model_manager.factory.class: Pantarei\Bundle\OAuth2Bundle\Entity\ModelManagerFactory

services:
    pantarei_oauth2.model_manager.factory:
        class: %pantarei_oauth2.model_manager.factory.class%
        arguments: ["@doctrine.orm.entity_manager", "%pantarei_oauth2.model%"]
