parameters:
    oauth2.model_manager.factory.class: PantaRei\Bundle\OAuth2Bundle\Entity\ModelManagerFactory

services:
    oauth2.model_manager.factory:
        class: %oauth2.model_manager.factory.class%
        arguments: ["@doctrine.orm.entity_manager", "%oauth2.model%"]
