oauth2_authorize_http:
    pattern: /oauth2/authorize/http
    defaults: { _controller: AuthBucketOAuth2Bundle:Authorize:authorize }
    methods: [GET]

oauth2_authorize_form:
    pattern: /oauth2/authorize/form
    defaults: { _controller: AuthBucketOAuth2Bundle:Authorize:authorize }
    methods: [GET]

oauth2_token:
    pattern: /oauth2/token
    defaults: { _controller: AuthBucketOAuth2Bundle:Token:token }
    methods: [POST]

oauth2_debug:
    pattern: /oauth2/debug
    defaults: { _controller: AuthBucketOAuth2Bundle:Debug:debug }
