pantarei_oauth2_authorize:
    pattern: /oauth2/authorize
    defaults: { _controller: PantareiOAuth2Bundle:Authorize:authorize }
    methods: [GET]

pantarei_oauth2_token:
    pattern: /oauth2/token
    defaults: { _controller: PantareiOAuth2Bundle:Token:token }
    methods: [POST]

pantarei_oauth2_resource_username:
    pattern: /oauth2/resource/username
    defaults: { _controller: PantareiOAuth2Bundle:Resource:username }
