oauth2_authorize:
    pattern: /authorize
    defaults: { _controller: AuthBucketOAuth2Bundle:Authorize:authorize }

oauth2_token:
    pattern: /token
    defaults: { _controller: AuthBucketOAuth2Bundle:Token:token }

oauth2_debug:
    pattern: /debug
    defaults: { _controller: AuthBucketOAuth2Bundle:Debug:debug }
