oauth2_authorize:
    pattern: /authorize
    defaults: { _controller: OAuth2Bundle:Authorize:authorize }
    methods: [GET]

oauth2_token:
    pattern: /token
    defaults: { _controller: OAuth2Bundle:Token:token }
    methods: [POST]

oauth2_resource_username:
    pattern: /resource/username
    defaults: { _controller: OAuth2Bundle:Resource:username }
