parameters:
    oauth2.exception_listener.class: PantaRei\OAuth2\EventListener\ExceptionListener

    oauth2.response_handler.factory.class: PantaRei\OAuth2\ResponseType\ResponseTypeHandlerFactory
    oauth2.grant_handler.factory.class: PantaRei\OAuth2\GrantType\GrantTypeHandlerFactory
    oauth2.token_handler.factory.class: PantaRei\OAuth2\TokenType\TokenTypeHandlerFactory

    oauth2.authorize_controller.class: PantaRei\OAuth2\Controller\AuthorizeController
    oauth2.token_controller.class: PantaRei\OAuth2\Controller\TokenController
    oauth2.resource_controller.class: PantaRei\OAuth2\Controller\ResourceController

    security.authentication.provider.token.class: PantaRei\OAuth2\Security\Authentication\Provider\TokenProvider
    security.authentication.listener.token.class: PantaRei\OAuth2\Security\Firewall\TokenListener

    security.authentication.provider.resource.class: PantaRei\OAuth2\Security\Authentication\Provider\ResourceProvider
    security.authentication.listener.resource.class: PantaRei\OAuth2\Security\Firewall\ResourceListener

services:
    oauth2.exception_listener:
        class: %oauth2.exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -8 }

    oauth2.response_handler.factory:
        class: %oauth2.response_handler.factory.class%
        arguments: ["%oauth2.response_handler%"]
    oauth2.grant_handler.factory:
        class: %oauth2.grant_handler.factory.class%
        arguments: ["%oauth2.grant_handler%"]
    oauth2.token_handler.factory:
        class: %oauth2.token_handler.factory.class%
        arguments: ["%oauth2.token_handler%"]

    oauth2.authorize_controller:
        class: %oauth2.authorize_controller.class%
        arguments: ["@security.context", "@oauth2.model_manager.factory", "@oauth2.response_handler.factory", "@oauth2.token_handler.factory"]
    oauth2.token_controller:
        class: %oauth2.token_controller.class%
        arguments: ["@security.context", "@security.user_checker", "@security.encoder_factory", "@oauth2.model_manager.factory", "@oauth2.grant_handler.factory", "@oauth2.token_handler.factory", null]
    oauth2.resource_controller:
        class: %oauth2.resource_controller.class%
        arguments: ["@security.context"]

    security.authentication.provider.token:
        class: %security.authentication.provider.token.class%
        arguments: ["@oauth2.model_manager.factory", ""]
    security.authentication.listener.token:
        class: %security.authentication.listener.token.class%
        arguments: ["@security.context", "@security.authentication.manager", ""]

    security.authentication.provider.resource:
        class: %security.authentication.provider.resource.class%
        arguments: ["@oauth2.model_manager.factory", ""]
    security.authentication.listener.resource:
        class: %security.authentication.listener.resource.class%
        arguments: ["@security.context", "@security.authentication.manager", "", "@oauth2.token_handler.factory"]
