parameters:
#    o_auth2.example.class: Pantarei\Bundle\OAuth2Bundle\Example

services:
#    o_auth2.example:
#        class: %o_auth2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
