parameters:
    authbucket_oauth2.exception_listener.class: AuthBucket\OAuth2\EventListener\ExceptionListener

    authbucket_oauth2.response_handler.factory.class: AuthBucket\OAuth2\ResponseType\ResponseTypeHandlerFactory
    authbucket_oauth2.grant_handler.factory.class: AuthBucket\OAuth2\GrantType\GrantTypeHandlerFactory
    authbucket_oauth2.token_handler.factory.class: AuthBucket\OAuth2\TokenType\TokenTypeHandlerFactory

    authbucket_oauth2.authorize_controller.class: AuthBucket\OAuth2\Controller\AuthorizeController
    authbucket_oauth2.token_controller.class: AuthBucket\OAuth2\Controller\TokenController
    authbucket_oauth2.resource_controller.class: AuthBucket\OAuth2\Controller\ResourceController

    security.authentication.provider.token.class: AuthBucket\OAuth2\Security\Authentication\Provider\TokenProvider
    security.authentication.listener.token.class: AuthBucket\OAuth2\Security\Firewall\TokenListener

    security.authentication.provider.resource.class: AuthBucket\OAuth2\Security\Authentication\Provider\ResourceProvider
    security.authentication.listener.resource.class: AuthBucket\OAuth2\Security\Firewall\ResourceListener

services:
    authbucket_oauth2.exception_listener:
        class: %authbucket_oauth2.exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -8 }

    authbucket_oauth2.response_handler.factory:
        class: %authbucket_oauth2.response_handler.factory.class%
        arguments: ["%authbucket_oauth2.response_handler%"]
    authbucket_oauth2.grant_handler.factory:
        class: %authbucket_oauth2.grant_handler.factory.class%
        arguments: ["%authbucket_oauth2.grant_handler%"]
    authbucket_oauth2.token_handler.factory:
        class: %authbucket_oauth2.token_handler.factory.class%
        arguments: ["%authbucket_oauth2.token_handler%"]

    authbucket_oauth2.authorize_controller:
        class: %authbucket_oauth2.authorize_controller.class%
        arguments: ["@security.context", "@authbucket_oauth2.model_manager.factory", "@authbucket_oauth2.response_handler.factory", "@authbucket_oauth2.token_handler.factory"]
    authbucket_oauth2.token_controller:
        class: %authbucket_oauth2.token_controller.class%
        arguments: ["@security.context", "@security.user_checker", "@security.encoder_factory", "@authbucket_oauth2.model_manager.factory", "@authbucket_oauth2.grant_handler.factory", "@authbucket_oauth2.token_handler.factory", null]
    authbucket_oauth2.resource_controller:
        class: %authbucket_oauth2.resource_controller.class%
        arguments: ["@security.context"]

    security.authentication.provider.token:
        class: %security.authentication.provider.token.class%
        arguments: ["@authbucket_oauth2.model_manager.factory", ""]
    security.authentication.listener.token:
        class: %security.authentication.listener.token.class%
        arguments: ["@security.context", "@security.authentication.manager", ""]

    security.authentication.provider.resource:
        class: %security.authentication.provider.resource.class%
        arguments: ["@authbucket_oauth2.model_manager.factory", ""]
    security.authentication.listener.resource:
        class: %security.authentication.listener.resource.class%
        arguments: ["@security.context", "@security.authentication.manager", "", "@authbucket_oauth2.token_handler.factory"]
