parameters:
    pantarei_oauth2.exception_listener.class: Pantarei\OAuth2\EventListener\ExceptionListener

    pantarei_oauth2.response_handler.factory.class: Pantarei\OAuth2\ResponseType\ResponseTypeHandlerFactory
    pantarei_oauth2.grant_handler.factory.class: Pantarei\OAuth2\GrantType\GrantTypeHandlerFactory
    pantarei_oauth2.token_handler.factory.class: Pantarei\OAuth2\TokenType\TokenTypeHandlerFactory

    pantarei_oauth2.authorize_controller.class: Pantarei\OAuth2\Controller\AuthorizeController
    pantarei_oauth2.token_controller.class: Pantarei\OAuth2\Controller\TokenController
    pantarei_oauth2.resource_controller.class: Pantarei\OAuth2\Controller\ResourceController

    security.authentication.provider.token.class: Pantarei\OAuth2\Security\Authentication\Provider\TokenProvider
    security.authentication.listener.token.class: Pantarei\OAuth2\Security\Firewall\TokenListener

    security.authentication.provider.resource.class: Pantarei\OAuth2\Security\Authentication\Provider\ResourceProvider
    security.authentication.listener.resource.class: Pantarei\OAuth2\Security\Firewall\ResourceListener

services:
    pantarei_oauth2.exception_listener:
        class: %pantarei_oauth2.exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -8 }

    pantarei_oauth2.response_handler.factory:
        class: %pantarei_oauth2.response_handler.factory.class%
        arguments: ["%pantarei_oauth2.response_handler%"]
    pantarei_oauth2.grant_handler.factory:
        class: %pantarei_oauth2.grant_handler.factory.class%
        arguments: ["%pantarei_oauth2.grant_handler%"]
    pantarei_oauth2.token_handler.factory:
        class: %pantarei_oauth2.token_handler.factory.class%
        arguments: ["%pantarei_oauth2.token_handler%"]

    pantarei_oauth2.authorize_controller:
        class: %pantarei_oauth2.authorize_controller.class%
        arguments: ["@security.context", "@pantarei_oauth2.model_manager.factory", "@pantarei_oauth2.response_handler.factory", "@pantarei_oauth2.token_handler.factory"]
    pantarei_oauth2.token_controller:
        class: %pantarei_oauth2.token_controller.class%
        arguments: ["@security.context", "@security.user_checker", "@security.encoder_factory", "@pantarei_oauth2.model_manager.factory", "@pantarei_oauth2.grant_handler.factory", "@pantarei_oauth2.token_handler.factory", null]
    pantarei_oauth2.resource_controller:
        class: %pantarei_oauth2.resource_controller.class%
        arguments: ["@security.context"]

    security.authentication.provider.token:
        class: %security.authentication.provider.token.class%
        arguments: ["@pantarei_oauth2.model_manager.factory", ""]
    security.authentication.listener.token:
        class: %security.authentication.listener.token.class%
        arguments: ["@security.context", "@security.authentication.manager", ""]

    security.authentication.provider.resource:
        class: %security.authentication.provider.resource.class%
        arguments: ["@pantarei_oauth2.model_manager.factory", ""]
    security.authentication.listener.resource:
        class: %security.authentication.listener.resource.class%
        arguments: ["@security.context", "@security.authentication.manager", "", "@pantarei_oauth2.token_handler.factory"]
