imports:
    - { resource: security.yml }

framework:
    secret:          fbe0b58410c7435d8b0afde3a2108fade7
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  en
    trusted_proxies: ~
    fragments:       ~
    test: ~
    session:
        storage_id:  session.storage.mock_file
    profiler:
        enabled:     false

# Twig Configuration
twig:
    debug:            true
    strict_variables: true

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path:   %kernel.cache_dir%/.ht.sqlite

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

authbucket_oauth2:
    driver:                 orm
    user_provider:          security.user.provider.concrete.default

    model:
        access_token:       AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\AccessToken
        authorize:          AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Authorize
        client:             AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Client
        code:               AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Code
        refresh_token:      AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\RefreshToken
        scope:              AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Scope

    response_handler:
        code:               AuthBucket\OAuth2\ResponseType\CodeResponseTypeHandler
        token:              AuthBucket\OAuth2\ResponseType\TokenResponseTypeHandler

    grant_handler:
        authorization_code: AuthBucket\OAuth2\GrantType\AuthorizationCodeGrantTypeHandler
        client_credentials: AuthBucket\OAuth2\GrantType\ClientCredentialsGrantTypeHandler
        password:           AuthBucket\OAuth2\GrantType\PasswordGrantTypeHandler
        refresh_token:      AuthBucket\OAuth2\GrantType\RefreshTokenGrantTypeHandler

    token_handler:
        bearer:             AuthBucket\OAuth2\TokenType\BearerTokenTypeHandler
        mac:                AuthBucket\OAuth2\TokenType\MacTokenTypeHandler

    resource_handler:
        model:              AuthBucket\OAuth2\ResourceType\ModelResourceTypeHandler
        debug_endpoint:     AuthBucket\OAuth2\ResourceType\DebugEndpointResourceTypeHandler
