security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        default:
            memory:
                users:
                    demousername1:  { roles: 'ROLE_USER', password: demopassword1 }
                    demousername2:  { roles: 'ROLE_USER', password: demopassword2 }
                    demousername3:  { roles: 'ROLE_USER', password: demopassword3 }

        admin:
            memory:
                users:
                    admin:          { roles: 'ROLE_ADMIN', password: secrete }

    firewalls:
        admin:
            pattern:                ^/admin
            http_basic:             ~
            provider:               admin

        oauth2_login:
            pattern:                ^/oauth2/login$
            anonymous:              ~

        oauth2_authorize_http:
            pattern:                ^/oauth2/authorize/http$
            http_basic:             ~
            provider:               default

        oauth2_authorize:
            pattern:                ^/oauth2/authorize
            form_login:
                login_path:         /oauth2/login
                check_path:         /oauth2/authorize/login_check
            logout:
                path:               /oauth2/authorize/logout
                target:             /demo
            provider:               default

        oauth2_token:
            pattern:                ^/oauth2/token$
            oauth2_token:           ~

        oauth2_debug:
            pattern:                ^/oauth2/debug$
            oauth2_resource:
                resource_type:      model
                scope:              [ debug ]

        resource_resource_type_model:
            pattern:                ^/resource/resource_type/model$
            oauth2_resource:
                resource_type:      model
                scope:              [ demoscope1 ]

        resource_resource_type_debug_endpoint:
            pattern:                ^/resource/resource_type/debug_endpoint$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    client_id:      'http://democlient1.com/'
                    client_secret:  'demosecret1'
                    cache:          false

        resource_resource_type_debug_endpoint_cache:
            pattern:                ^/resource/resource_type/debug_endpoint/cache$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    client_id:      'http://democlient1.com/'
                    client_secret:  'demosecret1'

        resource_resource_type_debug_endpoint_invalid_options:
            pattern:                ^/resource/resource_type/debug_endpoint/invalid_options$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:            ~

        resource_resource_type_debug_endpoint_invalid_client:
            pattern:                ^/resource/resource_type/debug_endpoint/invalid_client$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    client_id:      'nonexistsclient'
                    client_secret:  'fakesecret'
                    cache:          false
