security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        admin:
            memory:
                users:
                    admin:          { roles: 'ROLE_ADMIN', password: secrete }

        default:
            memory:
                users:
                    demousername1:  { roles: 'ROLE_USER', password: demopassword1 }
                    demousername2:  { roles: 'ROLE_USER', password: demopassword2 }
                    demousername3:  { roles: 'ROLE_USER', password: demopassword3 }

    firewalls:
        admin:
            pattern:                ^/admin
            http_basic:
                provider:           admin

        oauth2_login:
            pattern:                ^/oauth2/login$
            anonymous:              ~

        oauth2_authorize_http:
            pattern:                ^/oauth2/authorize/http$
            http_basic:
                provider:           default

        oauth2_authorize:
            pattern:                ^/oauth2/authorize
            form_login:
                login_path:         /oauth2/login
                check_path:         /oauth2/authorize/login_check
                provider:           default
            logout:
                path:               /oauth2/authorize/logout

        oauth2_token:
            pattern:                ^/oauth2/token$
            oauth2_token:           ~

        oauth2_debug:
            pattern:                ^/oauth2/debug$
            oauth2_resource:        
                resource_type:      model
                scope:              [ debug ]

        resource_debug:
            pattern:                ^/resource/debug$
            oauth2_resource:        ~

        resource_debug_model:
            pattern:                ^/resource/debug/model$
            oauth2_resource:
                resource_type:      model
                scope:              [ demoscope1 ]

        resource_debug_debug_endpoint:
            pattern:                ^/resource/debug/debug_endpoint$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    request_uri:    /oauth2/debug
                    client_id:      'http://democlient1.com/'
                    client_secret:  'demosecret1'
