api_oauth2_authorize:
    path:           /authorize
    defaults:       { _controller: AuthBucketOAuth2Bundle:Authorization:index }
    methods:        [ GET ]

api_oauth2_token:
    path:           /token
    defaults:       { _controller: AuthBucketOAuth2Bundle:Token:index }
    methods:        [ POST ]

api_oauth2_debug:
    path:           /debug
    defaults:       { _controller: AuthBucketOAuth2Bundle:Debug:index }
    methods:        [ GET|POST ]
