api_oauth2_authorize:
    path:           /api/oauth2/authorize
    defaults:       { _controller: AuthBucketOAuth2Bundle:OAuth2:authorize }
    methods:        [ GET ]

api_oauth2_token:
    path:           /api/oauth2/token
    defaults:       { _controller: AuthBucketOAuth2Bundle:OAuth2:token }
    methods:        [ POST ]

api_oauth2_debug:
    path:           /api/oauth2/debug
    defaults:       { _controller: AuthBucketOAuth2Bundle:OAuth2:debug }
    methods:        [ GET|POST ]
